#ifndef P1_PROGRAM_CONSTANTS_H
#define P1_PROGRAM_CONSTANTS_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define HEADER_HEIGHT 100
#define WINDOW_HEIGHT 770

#define SCROLLABLE_WINDOW_WIDTH 1100
#define SCROLLABLE_WINDOW_HEIGHT 440

// RESIDENT PAGE — SEARCHBAR
#define SEARCH_BAR_WIDTH 750
#define SEARCH_BAR_HEIGHT 45

// RESIDENT PAGE — SCROLLABLE WINDOW
#define SCROLLABLE_WINDOW_WIDTH 1100
#define SCROLLABLE_WINDOW_HEIGHT 440

#define ORDER_SCROLLABLE_WINDOW_WIDTH 900
#define ORDER_SCROLLABLE_WINDOW_HEIGHT 570

#define RESIDENT_PERSONAL_INFORMATION_AND_MEDICINE_WIDTH 400
#define LEFT_PANEL_HEIGHT 580
#define LEFT_PANEL_WIDTH 450
#define RIGHT_PANEL_HEIGHT 580
#define RIGHT_PANEL_WIDTH 750

// STORAGE PAGE — SCROLLABLE WINDOW
#define STORAGE_SCROLLABLE_WINDOW_WIDTH 900
#define STORAGE_SCROLLABLE_WINDOW_HEIGHT 450

#endif //P1_PROGRAM_CONSTANTS_H
